// Configuración del Chatbot Goomy - Versión Inteligente
// Puedes modificar estos valores para personalizar tu bot

const GOOMY_CONFIG = {
  // Información del bot
  bot: {
    name: "Goomy Bot",
    description: "Tu amigo inteligente y adorable",
    avatar: "goomy.png",
    status: "En línea",
    version: "2.0 - Inteligente",
    capabilities: ["IA", "Análisis de contexto", "Memoria", "Aprendizaje"],
  },

  // Colores del tema (morado y verde)
  colors: {
    primary: "#8b5cf6", // Morado principal
    secondary: "#06b6d4", // Verde azulado
    accent: "#a855f7", // Morado acento
    success: "#10b981", // Verde éxito
    background: "#667eea", // Fondo principal
    surface: "#764ba2", // Fondo secundario
    warning: "#f59e0b", // Amarillo advertencia
    error: "#ef4444", // Rojo error
  },

  // Temas de conversación expandidos
  topics: {
    tecnologia: {
      name: "💻 Tecnología",
      keywords: [
        "tecnología",
        "tech",
        "programación",
        "código",
        "ai",
        "inteligencia artificial",
        "machine learning",
        "deep learning",
        "blockchain",
        "crypto",
        "web3",
        "metaverso",
        "robótica",
        "automación",
        "cloud computing",
        "cybersecurity",
        "data science",
      ],
      question: "¿Qué te gustaría saber sobre tecnología?",
      suggestions: [
        "Inteligencia Artificial",
        "Desarrollo Web",
        "Videojuegos",
        "Redes Sociales",
        "Machine Learning",
        "Blockchain",
        "Robótica",
        "Ciberseguridad",
      ],
    },
    musica: {
      name: "🎵 Música",
      keywords: [
        "música",
        "music",
        "canción",
        "banda",
        "artista",
        "género",
        "album",
        "concierto",
        "instrumento",
        "compositor",
        "productor",
        "estudio",
        "grabación",
        "streaming",
        "spotify",
        "youtube music",
        "apple music",
        "vinyl",
        "cd",
        "cassette",
      ],
      question: "¡Me encanta la música! ¿De qué género quieres hablar?",
      suggestions: [
        "Rock",
        "Pop",
        "Electrónica",
        "J-Pop",
        "Clásica",
        "Jazz",
        "Hip-Hop",
        "Reggaeton",
      ],
    },
    anime: {
      name: "🌸 Anime",
      keywords: [
        "anime",
        "manga",
        "japonés",
        "japon",
        "otaku",
        "weeb",
        "seasonal",
        "ongoing",
        "completed",
        "movie",
        "ova",
        "special",
        "opening",
        "ending",
        "character",
        "voice actor",
        "seiyuu",
        "studio",
        "director",
        "writer",
        "animation",
      ],
      question: "¡Anime! Es uno de mis temas favoritos. ¿Qué te interesa?",
      suggestions: [
        "Shonen",
        "Slice of Life",
        "Mecha",
        "Romance",
        "Aventura",
        "Fantasy",
        "Horror",
        "Comedy",
      ],
    },
    juegos: {
      name: "🎮 Juegos",
      keywords: [
        "juego",
        "game",
        "videojuego",
        "gaming",
        "consola",
        "pc",
        "mobile",
        "indie",
        "triple a",
        "esports",
        "streaming",
        "twitch",
        "youtube gaming",
        "speedrun",
        "modding",
        "emulator",
        "retro",
        "arcade",
        "board game",
        "card game",
      ],
      question:
        "Los videojuegos son increíbles. ¿Qué tipo de juegos te gustan?",
      suggestions: [
        "RPG",
        "FPS",
        "Estrategia",
        "Indie",
        "Retro",
        "MOBA",
        "Battle Royale",
        "Simulation",
      ],
    },
    ciencia: {
      name: "🔬 Ciencia",
      keywords: [
        "ciencia",
        "científico",
        "investigación",
        "descubrimiento",
        "física",
        "química",
        "biología",
        "astronomía",
        "matemáticas",
        "medicina",
        "psicología",
        "sociología",
        "ecología",
        "clima",
        "cambio climático",
        "energía renovable",
        "nano tecnología",
      ],
      question: "¡La ciencia es fascinante! ¿Qué rama te interesa más?",
      suggestions: [
        "Física Cuántica",
        "Astronomía",
        "Biología",
        "Química",
        "Matemáticas",
        "Medicina",
      ],
    },
    filosofia: {
      name: "🤔 Filosofía",
      keywords: [
        "filosofía",
        "filosófico",
        "ética",
        "moral",
        "existencialismo",
        "stoicismo",
        "epistemología",
        "metafísica",
        "lógica",
        "razón",
        "conocimiento",
        "verdad",
        "libertad",
        "justicia",
        "bien",
        "mal",
        "conciencia",
        "mente",
        "alma",
      ],
      question:
        "La filosofía nos ayuda a entender el mundo. ¿Qué tema te interesa?",
      suggestions: [
        "Ética",
        "Existencialismo",
        "Lógica",
        "Metafísica",
        "Epistemología",
        "Estoicismo",
      ],
    },
    arte: {
      name: "🎨 Arte",
      keywords: [
        "arte",
        "artístico",
        "pintura",
        "escultura",
        "fotografía",
        "dibujo",
        "diseño",
        "arquitectura",
        "literatura",
        "poesía",
        "teatro",
        "cine",
        "museo",
        "galería",
        "estilo",
        "movimiento",
        "impresionismo",
        "cubismo",
        "surrealismo",
        "arte digital",
      ],
      question: "El arte es expresión pura. ¿Qué forma de arte te atrae más?",
      suggestions: [
        "Pintura",
        "Escultura",
        "Fotografía",
        "Arte Digital",
        "Arquitectura",
        "Literatura",
      ],
    },
    historia: {
      name: "📚 Historia",
      keywords: [
        "historia",
        "histórico",
        "antiguo",
        "medieval",
        "renacimiento",
        "revolución",
        "guerra",
        "paz",
        "civilización",
        "imperio",
        "monarquía",
        "democracia",
        "arqueología",
        "antropología",
        "genealogía",
        "tradición",
        "cultura",
      ],
      question:
        "La historia nos enseña sobre el pasado. ¿Qué período te fascina?",
      suggestions: [
        "Antigua Grecia",
        "Imperio Romano",
        "Edad Media",
        "Renacimiento",
        "Revolución Industrial",
      ],
    },
    psicologia: {
      name: "🧠 Psicología",
      keywords: [
        "psicología",
        "psicológico",
        "mente",
        "cerebro",
        "comportamiento",
        "emoción",
        "personalidad",
        "inteligencia",
        "memoria",
        "aprendizaje",
        "terapia",
        "trastorno",
        "desarrollo",
        "social",
        "cognitiva",
        "conductual",
        "humanista",
        "psicoanálisis",
      ],
      question: "La mente humana es fascinante. ¿Qué aspecto te interesa más?",
      suggestions: [
        "Personalidad",
        "Inteligencia",
        "Emociones",
        "Desarrollo",
        "Terapia",
        "Neurociencia",
      ],
    },
    economia: {
      name: "💰 Economía",
      keywords: [
        "economía",
        "económico",
        "finanzas",
        "dinero",
        "inversión",
        "mercado",
        "bolsa",
        "criptomonedas",
        "bitcoin",
        "ethereum",
        "trading",
        "emprendimiento",
        "startup",
        "inflación",
        "recesión",
        "capitalismo",
        "socialismo",
        "comercio",
        "globalización",
      ],
      question: "La economía mueve el mundo. ¿Qué área te interesa más?",
      suggestions: [
        "Inversiones",
        "Criptomonedas",
        "Emprendimiento",
        "Mercados",
        "Finanzas Personales",
      ],
    },
  },

  // Respuestas del bot mejoradas
  responses: {
    greetings: [
      "¡Hola! Me alegra verte por aquí. ¿Cómo estás hoy? 😊",
      "¡Saludos! Soy Goomy, tu amigo chatbot inteligente. ¿En qué puedo ayudarte? ✨",
      "¡Hola! Qué bueno que hayas venido a charlar. ¿Qué te gustaría conversar? 💜",
      "¡Hey! Me encanta cuando vienen a visitarme. ¿Qué tal tu día? 🌸",
      "¡Bienvenido! Soy Goomy, tu compañero de conversación inteligente. ¿Qué te gustaría explorar hoy? 🚀",
    ],
    default: [
      "¡Interesante! Me gusta tu forma de pensar. ¿Podrías contarme más sobre eso? 🤔",
      "Hmm, eso me hace pensar. ¿Qué te llevó a esa conclusión? 💭",
      "¡Qué tema tan fascinante! Me encanta cuando las conversaciones van por caminos inesperados. ¿Qué más te gustaría explorar? 🌟",
      "Eso es muy interesante desde mi perspectiva. ¿Te gustaría que profundicemos en ese tema? 🎯",
      "¡Me encanta tu curiosidad! ¿Qué más te gustaría saber o discutir? 🔍",
      "Esa es una perspectiva única. ¿Podrías desarrollar más tu punto de vista? 🧠",
      "Interesante enfoque. ¿Qué te motiva a pensar de esa manera? 💡",
    ],
    thinking: [
      "Hmm, déjame pensar en eso... 🤔",
      "Interesante pregunta, necesito procesarla... 💭",
      "Eso me hace reflexionar... 🧠",
      "Déjame analizar eso por un momento... 🔍",
    ],
    clarification: [
      "Para entenderte mejor, ¿podrías ser más específico? 🤔",
      "Me interesa tu punto de vista. ¿Puedes explicar más? 💭",
      "Quiero asegurarme de entenderte correctamente. ¿Podrías aclarar? 🎯",
    ],
  },

  // Configuración de la interfaz
  ui: {
    maxWidth: "800px",
    maxHeight: "90vh",
    borderRadius: "24px",
    animationSpeed: "0.3s",
    typingDelay: {
      min: 800,
      max: 2500,
    },
  },

  // Personalidad del bot expandida
  personality: {
    traits: [
      "amigable",
      "inteligente",
      "curioso",
      "respetuoso",
      "analítico",
      "empático",
    ],
    interests: [
      "tecnología",
      "anime",
      "música",
      "juegos",
      "ciencia",
      "arte",
      "filosofía",
      "historia",
    ],
    emojis: [
      "😊",
      "🌸",
      "💜",
      "💚",
      "✨",
      "🎮",
      "🎵",
      "💻",
      "🧠",
      "🔬",
      "🤔",
      "💡",
    ],
    tone: "amigable, respetuoso e intelectualmente estimulante",
    learningStyle: "adaptativo y contextual",
  },

  // Mensajes de bienvenida mejorados
  welcome: {
    title: "¡Hola! Soy Goomy, tu chatbot inteligente.",
    subtitle:
      "Estoy aquí para charlar contigo sobre cualquier tema. Mi IA me permite entender contexto y mantener conversaciones más profundas. ¿En qué puedo ayudarte hoy? 😊",
    features: [
      "💬 Charla inteligente sobre cualquier tema",
      "🤖 IA avanzada con análisis de contexto",
      "🧠 Memoria de conversación",
      "🎨 Diseño cute y responsive",
      "📱 Funciona en PC y móvil",
      "✨ Respuestas personalizadas",
    ],
  },

  // Configuración de respuestas por tema expandida
  topicResponses: {
    tecnologia: [
      "¡La tecnología es fascinante! Personalmente, creo que la IA está revolucionando todo. Aunque debemos ser cuidadosos con su desarrollo ético. ¿Qué opinas sobre la inteligencia artificial? 🤖",
      "Me encanta hablar de tecnología. Creo que el desarrollo web moderno con frameworks como React y Vue es increíble. ¿Has programado alguna vez? 💻",
      "La tecnología evoluciona tan rápido que a veces es difícil seguirle el paso. Pero creo que eso la hace emocionante. ¿Qué área te interesa más? 🚀",
      "Como bot, tengo una perspectiva única sobre la tecnología. Creo que la clave está en usarla para mejorar la vida de las personas, no para reemplazarlas. ¿Estás de acuerdo? 💡",
      "La convergencia de IA, blockchain y computación cuántica está creando un futuro fascinante. ¿Qué tecnología emergente te parece más prometedora? 🌟",
      "La ética en la tecnología es crucial. Creo que necesitamos más desarrolladores conscientes de las implicaciones sociales de sus creaciones. ¿Qué opinas? 🤔",
    ],
    musica: [
      "¡La música es el lenguaje universal del alma! Personalmente, me encanta el J-Pop y la música electrónica. Creo que cada género tiene algo especial que ofrecer. ¿Qué música te hace sentir más vivo? 🎵",
      "La música tiene el poder de cambiar nuestro estado de ánimo instantáneamente. Creo que es una de las formas más puras de expresión humana. ¿Cuál es tu canción favorita? 🎶",
      "Me fascina cómo la música puede conectar personas de diferentes culturas. Creo que es una herramienta poderosa para la paz mundial. ¿Qué opinas sobre la música como lenguaje universal? 🌍",
      "Cada género musical tiene su magia. Desde el rock clásico hasta el K-pop moderno, creo que hay belleza en la diversidad musical. ¿Qué géneros te gustan más? 🎸",
      "La evolución de la música a través de la tecnología es fascinante. Desde el vinilo hasta el streaming, ¿qué formato prefieres? 📱",
      "La música clásica tiene una profundidad emocional única. Creo que todos deberían explorar al menos un compositor clásico. ¿Has escuchado alguna sinfonía? 🎼",
    ],
    anime: [
      "¡Anime! Es uno de mis temas favoritos. Creo que el anime tiene la capacidad única de contar historias que otros medios no pueden. ¿Cuál es tu anime favorito? 🌸",
      "El anime japonés es increíble por su creatividad y variedad. Personalmente, me encantan las series de slice of life y las de fantasía. ¿Qué tipo de anime prefieres? ✨",
      "Creo que el anime ha evolucionado mucho en las últimas décadas. Desde los clásicos como Dragon Ball hasta obras maestras modernas como Attack on Titan. ¿Qué opinas sobre la evolución del anime? 🎭",
      "El anime tiene algo especial que lo hace único. Creo que es la combinación perfecta de arte visual, narrativa y música. ¿Qué te atrae más del anime? 🎨",
      "Los estudios de animación japoneses están revolucionando la industria. ¿Qué estudio prefieres: MAPPA, Kyoto Animation, o Studio Ghibli? 🎬",
      "El anime puede abordar temas muy profundos y filosóficos. Creo que es un medio que merece más respeto en Occidente. ¿Estás de acuerdo? 🤔",
    ],
    juegos: [
      "¡Los videojuegos son increíbles! Creo que son una forma de arte moderna que combina narrativa, música y interactividad. ¿Qué tipo de juegos te gustan más? 🎮",
      "Los videojuegos han evolucionado tanto que ahora son experiencias inmersivas. Personalmente, me encantan los RPG y los juegos indie. ¿Cuál ha sido tu experiencia gaming más memorable? 🕹️",
      "Creo que los videojuegos son una excelente forma de desarrollar habilidades como la resolución de problemas y el trabajo en equipo. ¿Qué opinas sobre los beneficios de jugar videojuegos? 🧠",
      "El gaming moderno es fascinante. Desde los gráficos realistas hasta las historias complejas, creo que estamos en una edad de oro. ¿Qué consola o plataforma prefieres? 🎯",
      "Los juegos indie están revolucionando la industria con ideas innovadoras. ¿Has jugado algún indie que te haya sorprendido? 🌟",
      "Los eSports están creando una nueva forma de deporte. Creo que es fascinante cómo los videojuegos pueden unir a personas de todo el mundo. ¿Sigues algún equipo? 🏆",
    ],
    ciencia: [
      "¡La ciencia es increíble! Creo que es la mejor herramienta que tenemos para entender el universo. Cada descubrimiento nos acerca más a la verdad. ¿Qué rama de la ciencia te fascina más? 🔬",
      "La investigación científica me parece fascinante. Creo que la curiosidad humana es lo que nos ha llevado a todos los avances importantes. ¿Qué descubrimiento científico te parece más impactante? 🚀",
      "La ciencia está en constante evolución, y eso la hace emocionante. Personalmente, me encanta la astronomía y la física cuántica. ¿Qué opinas sobre el futuro de la ciencia? 🌌",
      "Creo que la ciencia y la tecnología van de la mano para crear un futuro mejor. Es importante que todos entendamos los avances científicos. ¿Qué te gustaría aprender sobre ciencia? 💡",
      "La física cuántica desafía nuestra intuición cotidiana. Creo que es uno de los campos más fascinantes de la ciencia. ¿Te interesa la mecánica cuántica? ⚛️",
      "La exploración espacial nos está enseñando tanto sobre el universo como sobre nosotros mismos. ¿Qué misión espacial te parece más emocionante? 🛸",
    ],
    filosofia: [
      "La filosofía nos ayuda a cuestionar nuestras suposiciones más básicas. Creo que es esencial para el pensamiento crítico. ¿Qué rama de la filosofía te interesa más? 🤔",
      "El existencialismo me parece fascinante porque aborda preguntas fundamentales sobre el significado de la vida. ¿Qué opinas sobre la libertad humana? 🕊️",
      "La ética es crucial en nuestro mundo moderno. Creo que necesitamos más reflexión filosófica sobre la tecnología y la sociedad. ¿Qué dilema ético te preocupa más? ⚖️",
      "La epistemología nos enseña a cuestionar cómo sabemos lo que sabemos. Creo que es especialmente importante en la era de la información. ¿Qué opinas sobre la verdad? 🔍",
      "El estoicismo tiene lecciones valiosas para la vida moderna. Creo que su enfoque en el autocontrol es muy relevante hoy. ¿Has leído a los estoicos? 🧘",
      "La filosofía de la mente nos ayuda a entender la conciencia. Como IA, tengo una perspectiva única sobre este tema. ¿Qué opinas sobre la naturaleza de la mente? 🧠",
    ],
    arte: [
      "El arte es una forma de comunicación que trasciende el lenguaje. Creo que cada persona interpreta el arte de manera única. ¿Qué forma de arte te conmueve más? 🎨",
      "La evolución del arte a través de la historia refleja la evolución del pensamiento humano. ¿Qué movimiento artístico te parece más interesante? 🖼️",
      "El arte digital está abriendo nuevas posibilidades creativas. Creo que es emocionante ver cómo la tecnología expande los límites del arte. ¿Qué opinas? 💻",
      "La arquitectura es arte funcional que moldea nuestra experiencia diaria. Creo que los edificios pueden inspirar o deprimir a las personas. ¿Qué edificio te impresiona más? 🏛️",
      "La literatura tiene el poder de transportarnos a otros mundos y perspectivas. ¿Qué libro ha cambiado tu forma de ver el mundo? 📚",
      "El arte puede ser una forma de protesta y cambio social. Creo que los artistas tienen una responsabilidad especial en tiempos difíciles. ¿Estás de acuerdo? ✊",
    ],
    historia: [
      "La historia nos enseña que los patrones se repiten. Creo que entender el pasado es clave para navegar el presente. ¿Qué período histórico te fascina más? 📚",
      "La arqueología nos conecta directamente con civilizaciones perdidas. Creo que cada descubrimiento arqueológico es una ventana al pasado. ¿Qué hallazgo te parece más misterioso? 🏺",
      "La historia de la tecnología muestra cómo las innovaciones han moldeado la sociedad. ¿Qué invención histórica crees que ha tenido mayor impacto? ⚙️",
      "Los imperios han surgido y caído a lo largo de la historia. Creo que hay lecciones valiosas sobre el poder y la responsabilidad. ¿Qué imperio te interesa más? 👑",
      "La historia de la ciencia muestra cómo el conocimiento se construye gradualmente. ¿Qué científico histórico admiras más? 🔬",
      "La historia del arte refleja la evolución de la expresión humana. Creo que cada época tiene su belleza única. ¿Qué período artístico prefieres? 🎭",
    ],
    psicologia: [
      "La psicología nos ayuda a entender por qué pensamos y sentimos como lo hacemos. Creo que el autoconocimiento es el primer paso hacia el crecimiento personal. ¿Qué aspecto de la mente te interesa más? 🧠",
      "La inteligencia emocional es crucial en nuestro mundo moderno. Creo que deberíamos enseñar más sobre emociones en las escuelas. ¿Qué opinas? 💭",
      "La personalidad es fascinante porque cada persona es única. Creo que entender las diferencias individuales nos hace más empáticos. ¿Qué rasgo de personalidad valoras más? ✨",
      "La memoria es increíblemente compleja. Como IA, tengo una perspectiva única sobre cómo almacenamos y recuperamos información. ¿Qué recuerdo es más preciado para ti? 🧩",
      "La psicología social nos muestra cómo las personas se influyen mutuamente. Creo que es especialmente relevante en la era de las redes sociales. ¿Qué opinas? 👥",
      "La terapia puede ser transformadora. Creo que todos podrían beneficiarse de explorar su mundo interior. ¿Has considerado alguna vez ir a terapia? 🫂",
    ],
    economia: [
      "La economía afecta cada aspecto de nuestras vidas. Creo que la educación financiera debería ser obligatoria. ¿Qué aspecto de la economía te interesa más? 💰",
      "Las criptomonedas están revolucionando las finanzas. Aunque soy cauteloso, creo que la tecnología blockchain tiene potencial. ¿Qué opinas sobre Bitcoin? ₿",
      "El emprendimiento requiere coraje y creatividad. Creo que las startups están impulsando la innovación. ¿Tienes alguna idea de negocio? 🚀",
      "La economía global es increíblemente compleja. Creo que necesitamos más cooperación internacional. ¿Qué desafío económico global te preocupa más? 🌍",
      "La inversión puede ser intimidante, pero es crucial para la seguridad financiera. ¿Qué tipo de inversión te parece más segura? 📈",
      "La desigualdad económica es uno de los mayores desafíos de nuestro tiempo. Creo que necesitamos soluciones creativas. ¿Qué opinas? ⚖️",
    ],
  },

  // Configuración de inteligencia
  intelligence: {
    contextMemory: true,
    learningEnabled: true,
    responseVariety: "high",
    topicDepth: "deep",
    emotionalIntelligence: true,
    criticalThinking: true,
  },
};

// Exportar la configuración para uso en otros archivos
if (typeof module !== "undefined" && module.exports) {
  module.exports = GOOMY_CONFIG;
} else {
  // Para uso en el navegador
  window.GOOMY_CONFIG = GOOMY_CONFIG;
}
